### PR TITLE
Fix syntax issues that causes tsc build failure

### LINKED ISSUE #113: update typos for aqasystemtestsRepo
There are two typos for aqasystemtestsRepo, which was typed as aqa-systemtestsRepo.  Due to https://github.com/adoptium/run-aqa/issues/104 we didn't notice this issue early. 

`aqa-systemtestsRepo` should be replaced as  `aqasystemtestsRepo` in https://github.com/adoptium/run-aqa/blob/master/src/runaqa.ts#L63

### PR DESCRIPTION
**Pull request by renfeiw**
- fix ts file errors and generate new js file

Fix #113 

Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Review by smlambert — APPROVED** [review]
LGTM

File: dist/index.js [hunk 1]
```diff
@@ -3562,16 +3563,11 @@ function getAqaTestsRepo(aqatestsRepo) {
...
-
 function getAqaSystemTestsRepo(aqasystemtestsRepo) {
-  let repoBranch = ['adoptium/aqa-systemtests', 'master'];
-  if (aqasystemtestsRepo.length !== 0) {
-      repoBranch = parseRepoBranch(aqasystemtestsRepo);
-  }
-  process.env.ADOPTOPENJDK_SYSTEMTEST_REPO = repoBranch[0];
-  process.env.ADOPTOPENJDK_SYSTEMTEST_BRANCH = repoBranch[1];
+    const repoBranch = parseRepoBranch(aqasystemtestsRepo);
+    process.env.ADOPTOPENJDK_SYSTEMTEST_REPO = repoBranch[0];
```
Comment (sophia-guo) [inline dist/index.js:3568]: This probably won't work. See #115

File: src/runaqa.ts [hunk 2]
```diff
@@ -233,10 +233,10 @@ async function getAqaTestsRepo(aqatestsRepo: string): Promise<void> {
   process.chdir('aqa-tests')
 }
 
-function getAqaSystemTestsRepo(aqasystemtestsRepo: string) {
+function getAqaSystemTestsRepo(aqasystemtestsRepo: string): void {
   const repoBranch = parseRepoBranch(aqasystemtestsRepo)
-  process.env.ADOPTOPENJDK_SYSTEMTEST_REPO = repoBranch[0];
-  process.env.ADOPTOPENJDK_SYSTEMTEST_BRANCH = repoBranch[1];
+  process.env.ADOPTOPENJDK_SYSTEMTEST_REPO = repoBranch[0]
```
Comment (sophia-guo) [inline src/runaqa.ts:238]: This probably won't work. env.ADOPTOPENJDK_SYSTEMTEST_REPO is the whole git url. See #115

Comment (sophia-guo) [reply src/runaqa.ts:238]: #115 can be done in a separate PR, which only affects system tests. Talked with @renfeiw we can let this in first.

**Review by sophia-guo — APPROVED** [review]
LGTM
